In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies.csv")
df.head(3)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [3]:
df.shape

(37, 10)

In [4]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [5]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [6]:
df["profit"] = df.apply(lambda x: x['revenue'] - x['budget'], axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0

In [7]:
df_movies = pd.read_excel("movies_db.xlsx", "movies")
df_movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [8]:
df_financials = pd.read_excel("movies_db.xlsx", "financials")
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [9]:
def standardize_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials = pd.read_excel("movies_db.xlsx", "financials", converters = {
    'currency': standardize_currency
})
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD