In [1]:
import pandas as pd
df = pd.read_csv('./ML_dataset/salaries.csv')
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [6]:
inputs = df.drop('salary_more_then_100k', axis='columns')
target = df['salary_more_then_100k']

In [7]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [9]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])
inputs.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [11]:
inputs_n = inputs.drop(['company', 'job', 'degree'], axis='columns')
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [12]:
from sklearn import tree

In [13]:
model = tree.DecisionTreeClassifier()

In [14]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [15]:
model.score(inputs_n, target)

1.0

In [25]:
for i in sorted(inputs_n['company_n'].unique()):
    print(f"Number label: {i} and Company name: {le_company.inverse_transform([i])[0]}")

Number label: 0 and Company name: abc pharma
Number label: 1 and Company name: facebook
Number label: 2 and Company name: google

In [27]:
for i in sorted(inputs_n['job_n'].unique()):
    print(f"Number label: {i} and Job name: {le_job.inverse_transform([i])[0]}")

Number label: 0 and Job name: business manager
Number label: 1 and Job name: computer programmer
Number label: 2 and Job name: sales executive

In [28]:
for i in sorted(inputs_n['degree_n'].unique()):
    print(f"Number label: {i} and Degree name: {le_degree.inverse_transform([i])[0]}")

Number label: 0 and Degree name: bachelors
Number label: 1 and Degree name: masters

In [29]:
model.predict([[2,0,1]])

/home/raul/Github/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

---

## Exercise

Exercise: Build decision tree model to predict survival based on certain parameters


CSV file is available to download at https://github.com/codebasics/py/blob/master/ML/9_decision_tree/Exercise/titanic.csv

In this file using following columns build a model to predict if person would survive or not,
1. Pclass
2. Sex
3. Age
4. Fare

Calculate score of your model

In [54]:
df = pd.read_csv('./ML_dataset/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [56]:
df = df[['Survived','Pclass', 'Sex', 'Age', 'Fare']]

In [57]:
df = df.dropna()
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
885         0       3  female  39.0  29.1250
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[714 rows x 5 columns]

In [58]:
df_inputs = df[['Pclass', 'Sex', 'Age', 'Fare']]
df_target = df['Survived']

In [59]:
df_inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
885       3  female  39.0  29.1250
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[714 rows x 4 columns]

In [60]:
df_target

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [61]:
df_inputs.count()

Pclass    714
Sex       714
Age       714
Fare      714
dtype: int64

In [64]:
df_target.count()

714

In [65]:
le_sex = LabelEncoder()

In [66]:
df_inputs['Sex_n'] = le_sex.fit_transform(df_inputs['Sex'])
df_inputs = df_inputs.drop(['Sex'], axis='columns')
df_inputs

     Pclass   Age     Fare  Sex_n
0         3  22.0   7.2500      1
1         1  38.0  71.2833      0
2         3  26.0   7.9250      0
3         1  35.0  53.1000      0
4         3  35.0   8.0500      1
..      ...   ...      ...    ...
885       3  39.0  29.1250      0
886       2  27.0  13.0000      1
887       1  19.0  30.0000      0
889       1  26.0  30.0000      1
890       3  32.0   7.7500      1

[714 rows x 4 columns]

In [67]:
model = tree.DecisionTreeClassifier()

In [69]:
model.fit(df_inputs, df_target)

DecisionTreeClassifier()

In [71]:
model.score(df_inputs, df_target)

0.9845938375350141

In [75]:
for i in sorted(df_inputs['Sex_n'].unique()):
    print(f"Number Label: {i} -> Sex: {le_sex.inverse_transform([i])[0]}")

Number Label: 0 -> Sex: female
Number Label: 1 -> Sex: male

In [93]:
model.predict([[3,1,2,0]])

/home/raul/Github/Training/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])